var COMPODOC_SEARCH_INDEX = {
    index: {
        version: '2.3.9',
        fields: ['title', 'body'],
        fieldVectors: [
            ['title/coverage.html', [0, 1.025]],
            [
                'body/coverage.html',
                [
                    0,
                    0.88,
                    1,
                    1.955,
                    2,
                    1.307,
                    3,
                    1.955,
                    4,
                    1.955,
                    5,
                    1.307,
                    6,
                    0.88,
                    7,
                    1.307,
                    8,
                    1.307,
                    9,
                    0.094,
                    10,
                    0.119,
                    11,
                    0.119,
                    12,
                    0.094,
                ],
            ],
            ['title/dependencies.html', [13, 1.466, 14, 1.368]],
            [
                'body/dependencies.html',
                [
                    9,
                    0.064,
                    10,
                    0.092,
                    11,
                    0.146,
                    12,
                    0.064,
                    14,
                    0.891,
                    15,
                    1.333,
                    16,
                    1.899,
                    17,
                    1.333,
                    18,
                    1.333,
                    19,
                    1.333,
                    20,
                    1.333,
                    21,
                    1.914,
                    22,
                    1.914,
                    23,
                    1.333,
                    24,
                    1.333,
                    25,
                    1.333,
                    26,
                    1.333,
                    27,
                    1.333,
                    28,
                    1.333,
                    29,
                    1.333,
                    30,
                    1.333,
                ],
            ],
            ['title/index.html', [31, 1.466, 32, 1.466, 33, 1.466]],
            [
                'body/index.html',
                [
                    6,
                    0.369,
                    9,
                    0.039,
                    10,
                    0.064,
                    11,
                    0.064,
                    12,
                    0.039,
                    16,
                    0.548,
                    34,
                    0.821,
                    35,
                    1.321,
                    36,
                    0.821,
                    37,
                    1.659,
                    38,
                    1.659,
                    39,
                    0.821,
                    40,
                    0.821,
                    41,
                    1.321,
                    42,
                    2.084,
                    43,
                    2.342,
                    44,
                    0.821,
                    45,
                    0.821,
                    46,
                    0.821,
                    47,
                    0.821,
                    48,
                    0.821,
                    49,
                    0.821,
                    50,
                    0.821,
                    51,
                    0.821,
                    52,
                    0.821,
                    53,
                    0.821,
                    54,
                    0.821,
                    55,
                    0.821,
                    56,
                    1.659,
                    57,
                    1.659,
                    58,
                    0.821,
                    59,
                    1.659,
                    60,
                    0.821,
                    61,
                    2.084,
                    62,
                    0.821,
                    63,
                    0.821,
                    64,
                    0.821,
                    65,
                    0.821,
                    66,
                    0.821,
                    67,
                    0.821,
                    68,
                    0.821,
                    69,
                    1.321,
                    70,
                    0.595,
                    71,
                    1.901,
                    72,
                    0.369,
                    73,
                    1.321,
                    74,
                    1.321,
                    75,
                    0.821,
                    76,
                    1.901,
                    77,
                    0.821,
                    78,
                    0.821,
                    79,
                    0.821,
                    80,
                    1.659,
                    81,
                    0.821,
                    82,
                    0.821,
                    83,
                    0.821,
                    84,
                    0.821,
                    85,
                    0.821,
                ],
            ],
            ['title/modules.html', [86, 1.523]],
            [
                'body/modules.html',
                [9, 0.109, 10, 0.13, 11, 0.13, 12, 0.109, 86, 1.508],
            ],
            ['title/overview.html', [87, 1.523]],
            [
                'body/overview.html',
                [9, 0.109, 10, 0.13, 11, 0.13, 12, 0.109, 87, 1.508],
            ],
            ['title/unit-test.html', [70, 0.836, 72, 0.836]],
            [
                'body/unit-test.html',
                [
                    0,
                    0.851,
                    2,
                    1.265,
                    5,
                    1.265,
                    6,
                    0.851,
                    7,
                    1.265,
                    8,
                    1.265,
                    9,
                    0.091,
                    10,
                    0.117,
                    11,
                    0.117,
                    12,
                    0.091,
                    70,
                    0.851,
                    72,
                    0.851,
                    88,
                    1.892,
                    89,
                    1.892,
                    90,
                    1.892,
                ],
            ],
        ],
        invertedIndex: [
            [
                '',
                {
                    _index: 11,
                    title: {},
                    body: {
                        'coverage.html': {},
                        'dependencies.html': {},
                        'index.html': {},
                        'modules.html': {},
                        'overview.html': {},
                        'unit-test.html': {},
                    },
                },
            ],
            [
                '0.10.2',
                { _index: 30, title: {}, body: { 'dependencies.html': {} } },
            ],
            [
                '1.10.0',
                { _index: 28, title: {}, body: { 'dependencies.html': {} } },
            ],
            [
                '6.5.4',
                { _index: 26, title: {}, body: { 'dependencies.html': {} } },
            ],
            [
                '9.1.0',
                {
                    _index: 16,
                    title: {},
                    body: { 'dependencies.html': {}, 'index.html': {} },
                },
            ],
            ['angular', { _index: 37, title: {}, body: { 'index.html': {} } }],
            [
                'angular/animations',
                { _index: 15, title: {}, body: { 'dependencies.html': {} } },
            ],
            [
                'angular/common',
                { _index: 17, title: {}, body: { 'dependencies.html': {} } },
            ],
            [
                'angular/compiler',
                { _index: 18, title: {}, body: { 'dependencies.html': {} } },
            ],
            [
                'angular/core',
                { _index: 19, title: {}, body: { 'dependencies.html': {} } },
            ],
            [
                'angular/forms',
                { _index: 20, title: {}, body: { 'dependencies.html': {} } },
            ],
            [
                'angular/platform',
                { _index: 21, title: {}, body: { 'dependencies.html': {} } },
            ],
            [
                'angular/router',
                { _index: 24, title: {}, body: { 'dependencies.html': {} } },
            ],
            ['app', { _index: 48, title: {}, body: { 'index.html': {} } }],
            [
                'artifacts',
                { _index: 62, title: {}, body: { 'index.html': {} } },
            ],
            [
                'automatically',
                { _index: 49, title: {}, body: { 'index.html': {} } },
            ],
            [
                'branches',
                { _index: 88, title: {}, body: { 'unit-test.html': {} } },
            ],
            [
                'browser',
                { _index: 22, title: {}, body: { 'dependencies.html': {} } },
            ],
            ['build', { _index: 61, title: {}, body: { 'index.html': {} } }],
            ['change', { _index: 51, title: {}, body: { 'index.html': {} } }],
            ['check', { _index: 83, title: {}, body: { 'index.html': {} } }],
            ['cli', { _index: 38, title: {}, body: { 'index.html': {} } }],
            ['code', { _index: 54, title: {}, body: { 'index.html': {} } }],
            [
                'component',
                { _index: 57, title: {}, body: { 'index.html': {} } },
            ],
            [
                'coverage',
                {
                    _index: 0,
                    title: { 'coverage.html': {} },
                    body: { 'coverage.html': {}, 'unit-test.html': {} },
                },
            ],
            [
                'dependencies',
                {
                    _index: 14,
                    title: { 'dependencies.html': {} },
                    body: { 'dependencies.html': {} },
                },
            ],
            ['dev', { _index: 45, title: {}, body: { 'index.html': {} } }],
            [
                'development',
                { _index: 40, title: {}, body: { 'index.html': {} } },
            ],
            [
                'directive|pipe|service|class|guard|interface|enum|module',
                { _index: 60, title: {}, body: { 'index.html': {} } },
            ],
            [
                'directory',
                { _index: 65, title: {}, body: { 'index.html': {} } },
            ],
            ['dist', { _index: 64, title: {}, body: { 'index.html': {} } }],
            [
                'documentation',
                { _index: 1, title: {}, body: { 'coverage.html': {} } },
            ],
            [
                'dynamic',
                { _index: 23, title: {}, body: { 'dependencies.html': {} } },
            ],
            ['e2e', { _index: 77, title: {}, body: { 'index.html': {} } }],
            ['end', { _index: 76, title: {}, body: { 'index.html': {} } }],
            ['execute', { _index: 73, title: {}, body: { 'index.html': {} } }],
            [
                'file',
                {
                    _index: 2,
                    title: {},
                    body: { 'coverage.html': {}, 'unit-test.html': {} },
                },
            ],
            ['files', { _index: 53, title: {}, body: { 'index.html': {} } }],
            ['flag', { _index: 67, title: {}, body: { 'index.html': {} } }],
            ['frontend', { _index: 34, title: {}, body: { 'index.html': {} } }],
            [
                'functions',
                { _index: 89, title: {}, body: { 'unit-test.html': {} } },
            ],
            ['further', { _index: 79, title: {}, body: { 'index.html': {} } }],
            ['generate', { _index: 56, title: {}, body: { 'index.html': {} } }],
            [
                'generated',
                { _index: 36, title: {}, body: { 'index.html': {} } },
            ],
            ['getting', { _index: 31, title: { 'index.html': {} }, body: {} }],
            ['go', { _index: 82, title: {}, body: { 'index.html': {} } }],
            ['help', { _index: 80, title: {}, body: { 'index.html': {} } }],
            [
                'http://localhost:4200',
                { _index: 47, title: {}, body: { 'index.html': {} } },
            ],
            [
                'identifier',
                { _index: 4, title: {}, body: { 'coverage.html': {} } },
            ],
            ['index', { _index: 33, title: { 'index.html': {} }, body: {} }],
            ['karma', { _index: 75, title: {}, body: { 'index.html': {} } }],
            [
                'lines',
                { _index: 90, title: {}, body: { 'unit-test.html': {} } },
            ],
            [
                'matching',
                {
                    _index: 10,
                    title: {},
                    body: {
                        'coverage.html': {},
                        'dependencies.html': {},
                        'index.html': {},
                        'modules.html': {},
                        'overview.html': {},
                        'unit-test.html': {},
                    },
                },
            ],
            [
                'modules',
                {
                    _index: 86,
                    title: { 'modules.html': {} },
                    body: { 'modules.html': {} },
                },
            ],
            ['more', { _index: 81, title: {}, body: { 'index.html': {} } }],
            ['name', { _index: 58, title: {}, body: { 'index.html': {} } }],
            ['navigate', { _index: 46, title: {}, body: { 'index.html': {} } }],
            [
                'new',
                {
                    _index: 6,
                    title: {},
                    body: {
                        'coverage.html': {},
                        'index.html': {},
                        'unit-test.html': {},
                    },
                },
            ],
            ['ng', { _index: 43, title: {}, body: { 'index.html': {} } }],
            ['out', { _index: 84, title: {}, body: { 'index.html': {} } }],
            [
                'overview',
                {
                    _index: 87,
                    title: { 'overview.html': {} },
                    body: { 'overview.html': {} },
                },
            ],
            [
                'package',
                { _index: 13, title: { 'dependencies.html': {} }, body: {} },
            ],
            ['prod', { _index: 66, title: {}, body: { 'index.html': {} } }],
            [
                'production',
                { _index: 68, title: {}, body: { 'index.html': {} } },
            ],
            ['project', { _index: 35, title: {}, body: { 'index.html': {} } }],
            [
                'protractor',
                { _index: 78, title: {}, body: { 'index.html': {} } },
            ],
            ['readme', { _index: 85, title: {}, body: { 'index.html': {} } }],
            ['reload', { _index: 50, title: {}, body: { 'index.html': {} } }],
            [
                'result',
                {
                    _index: 9,
                    title: {},
                    body: {
                        'coverage.html': {},
                        'dependencies.html': {},
                        'index.html': {},
                        'modules.html': {},
                        'overview.html': {},
                        'unit-test.html': {},
                    },
                },
            ],
            [
                'results',
                {
                    _index: 12,
                    title: {},
                    body: {
                        'coverage.html': {},
                        'dependencies.html': {},
                        'index.html': {},
                        'modules.html': {},
                        'overview.html': {},
                        'unit-test.html': {},
                    },
                },
            ],
            ['run', { _index: 42, title: {}, body: { 'index.html': {} } }],
            ['running', { _index: 69, title: {}, body: { 'index.html': {} } }],
            [
                'rxjs',
                { _index: 25, title: {}, body: { 'dependencies.html': {} } },
            ],
            [
                'scaffolding',
                { _index: 55, title: {}, body: { 'index.html': {} } },
            ],
            ['serve', { _index: 44, title: {}, body: { 'index.html': {} } }],
            ['server', { _index: 41, title: {}, body: { 'index.html': {} } }],
            ['source', { _index: 52, title: {}, body: { 'index.html': {} } }],
            ['started', { _index: 32, title: { 'index.html': {} }, body: {} }],
            [
                'statements',
                {
                    _index: 5,
                    title: {},
                    body: { 'coverage.html': {}, 'unit-test.html': {} },
                },
            ],
            ['stored', { _index: 63, title: {}, body: { 'index.html': {} } }],
            [
                'table',
                {
                    _index: 8,
                    title: {},
                    body: { 'coverage.html': {}, 'unit-test.html': {} },
                },
            ],
            [
                "tablesort(document.getelementbyid('coverage",
                {
                    _index: 7,
                    title: {},
                    body: { 'coverage.html': {}, 'unit-test.html': {} },
                },
            ],
            [
                'test',
                {
                    _index: 72,
                    title: { 'unit-test.html': {} },
                    body: { 'index.html': {}, 'unit-test.html': {} },
                },
            ],
            ['tests', { _index: 71, title: {}, body: { 'index.html': {} } }],
            [
                'tslib',
                { _index: 27, title: {}, body: { 'dependencies.html': {} } },
            ],
            ['type', { _index: 3, title: {}, body: { 'coverage.html': {} } }],
            [
                'unit',
                {
                    _index: 70,
                    title: { 'unit-test.html': {} },
                    body: { 'index.html': {}, 'unit-test.html': {} },
                },
            ],
            ['use', { _index: 59, title: {}, body: { 'index.html': {} } }],
            ['version', { _index: 39, title: {}, body: { 'index.html': {} } }],
            ['via', { _index: 74, title: {}, body: { 'index.html': {} } }],
            [
                'zone.js',
                { _index: 29, title: {}, body: { 'dependencies.html': {} } },
            ],
        ],
        pipeline: ['stemmer'],
    },
    store: {
        'coverage.html': {
            url: 'coverage.html',
            title: 'coverage - coverage',
            body:
                '\n                   \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                   \n\n\n\n    Documentation coverage\n\n\n\n    \n\n\n\n    \n        \n            File\n            Type\n            Identifier\n            Statements\n        \n    \n    \n    \n\n\n\n\n\n    new Tablesort(document.getElementById(\'coverage-table\'));\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
        },
        'dependencies.html': {
            url: 'dependencies.html',
            title: 'package-dependencies - dependencies',
            body:
                '\n                   \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n    \n        Dependencies\n    \n    \n        \n            @angular/animations : ~9.1.0\n        \n            @angular/common : ~9.1.0\n        \n            @angular/compiler : ~9.1.0\n        \n            @angular/core : ~9.1.0\n        \n            @angular/forms : ~9.1.0\n        \n            @angular/platform-browser : ~9.1.0\n        \n            @angular/platform-browser-dynamic : ~9.1.0\n        \n            @angular/router : ~9.1.0\n        \n            rxjs : ~6.5.4\n        \n            tslib : ^1.10.0\n        \n            zone.js : ~0.10.2\n    \n\n                   \n\n\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
        },
        'index.html': {
            url: 'index.html',
            title: 'getting-started - index',
            body:
                '\n                   \n\nFrontend\nThis project was generated with Angular CLI version 9.1.0.\nDevelopment server\nRun ng serve for a dev server. Navigate to http://localhost:4200/. The app will automatically reload if you change any of the source files.\nCode scaffolding\nRun ng generate component component-name to generate a new component. You can also use ng generate directive|pipe|service|class|guard|interface|enum|module.\nBuild\nRun ng build to build the project. The build artifacts will be stored in the dist/ directory. Use the --prod flag for a production build.\nRunning unit tests\nRun ng test to execute the unit tests via Karma.\nRunning end-to-end tests\nRun ng e2e to execute the end-to-end tests via Protractor.\nFurther help\nTo get more help on the Angular CLI use ng help or go check out the Angular CLI README.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                   \n\n\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
        },
        'modules.html': {
            url: 'modules.html',
            title: 'modules - modules',
            body:
                '\n                   \n\n\n\n\n    Modules\n\n\n    \n    \n\n\n\n\n\n\n\n\n\n\n\n\n                   \n\n\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
        },
        'overview.html': {
            url: 'overview.html',
            title: 'overview - overview',
            body:
                '\n                   \n\n\n\n    Overview\n\n    \n\n    \n    \n\n\n \n\n\n\n\n\n\n\n\n\n\n\n                   \n\n\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
        },
        'unit-test.html': {
            url: 'unit-test.html',
            title: 'unit-test - unit-test',
            body:
                '\n                   \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                   \n\n\n\n\n  Unit test coverage\n\n\n\n    \n    \n    \n    \n\n\n\n    \n        \n            File\n            Statements\n            Branches\n            Functions\n            Lines\n        \n    \n    \n    \n\n\n\n\n\n    new Tablesort(document.getElementById(\'coverage-table\'));\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
        },
    },
}
